version: "3.8"
services:
  backend:
    build:
      context: ../ecommerce-backend
    env_file:
      - ../ecommerce-backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_BASE_URL=http://localhost:8080
    restart: unless-stopped
